num-threads: 4
max-connections: 4096
error-log: /tmp/atomos-bench-h2o.err
pid-file: /tmp/atomos-bench-h2o.pid
listen: 18093
hosts:
  "127.0.0.1:18093":
    paths:
      "/":
        file.dir: ROOT
        file.send-gzip: OFF
