#!/usr/bin/env bash
# Derive cargo/rustc CPU flags from this machine's /proc/cpuinfo.
# No hardcoded microarch name (no "broadwell"). Uses target-cpu=native
# plus explicit AVX features that are present, and -avx512* / -avx10*
# when the CPU does not advertise them (so we never emit zmm here).
#
# Usage:
#   scripts/cpu-rustflags.sh              # print rustc -C args
#   scripts/cpu-rustflags.sh features     # print detected avx* flags
#   eval "$(scripts/cpu-rustflags.sh export)"
#   scripts/cpu-rustflags.sh write [REPO] # rewrite REPO/.cargo/config.toml
#   scripts/cpu-rustflags.sh cargo test --offline
#
# Environment RUSTFLAGS replaces .cargo/config.toml rustflags. Unset a
# host-wide mold RUSTFLAGS before relying on this file.

set -euo pipefail

cpuinfo_flags() {
  if [[ -r /proc/cpuinfo ]]; then
    grep -m1 -E '^flags[[:space:]]*:' /proc/cpuinfo \
      | sed 's/^[^:]*:[[:space:]]*//' \
      | tr '[:upper:]' '[:lower:]'
    return 0
  fi
  echo "cpu-rustflags: cannot read /proc/cpuinfo" >&2
  return 1
}

has_flag() {
  local needle=" $1 "
  local hay=" $2 "
  [[ "$hay" == *"$needle"* ]]
}

# Linux cpuinfo name -> rustc target-feature name. Only AVX family.
# avx10 is reported as avx10.1 / avx10_1 depending on kernel; we accept both.
AVX512_RUSTC=(
  avx512f
  avx512cd
  avx512dq
  avx512bw
  avx512vl
  avx512ifma
  avx512vbmi
  avx512vbmi2
  avx512vnni
  avx512bitalg
  avx512vpopcntdq
  avx512bf16
  avx512vp2intersect
  avx512fp16
)

linux_has_avx512() {
  local flags="$1"
  has_flag avx512f "$flags" || has_flag avx512 "$flags"
}

linux_has_avx10() {
  local flags="$1"
  has_flag avx10.1 "$flags" || has_flag avx10_1 "$flags" || has_flag avx10 "$flags"
}

detect_avx() {
  local flags present=()
  flags=$(cpuinfo_flags)
  if has_flag avx "$flags"; then present+=(avx); fi
  if has_flag avx2 "$flags"; then present+=(avx2); fi
  if linux_has_avx512 "$flags"; then
    local f
    for f in "${AVX512_RUSTC[@]}"; do
      if has_flag "$f" "$flags"; then
        present+=("$f")
      fi
    done
    # avx512f is the gate; if only the umbrella bit exists, still enable f.
    local joined=" ${present[*]} "
    if [[ "$joined" != *" avx512f "* ]]; then
      present+=(avx512f)
    fi
  fi
  if linux_has_avx10 "$flags"; then
    present+=("avx10.1")
  fi
  printf '%s\n' "${present[@]}"
}

target_feature_csv() {
  local flags present=() f
  flags=$(cpuinfo_flags)
  mapfile -t present < <(detect_avx)

  local parts=()
  for f in "${present[@]}"; do
    parts+=("+$f")
  done

  if ! linux_has_avx512 "$flags"; then
    for f in "${AVX512_RUSTC[@]}"; do
      parts+=("-$f")
    done
  fi
  if ! linux_has_avx10 "$flags"; then
    # Only names rustc accepts without "unknown feature" noise.
    parts+=("-avx10.1" "-avx10.2")
  fi

  local IFS=,
  echo "${parts[*]}"
}

rustc_c_args() {
  local feat
  feat=$(target_feature_csv)
  printf '%s\n' \
    "-C" "target-cpu=native" \
    "-C" "target-feature=${feat}" \
    "-C" "link-arg=-fuse-ld=lld" \
    "-C" "link-arg=-Wl,-z,relro,-z,now,-z,noexecstack"
}

toml_rustflags_array() {
  local feat
  feat=$(target_feature_csv)
  cat <<EOF
[
  "-C", "target-cpu=native",
  "-C", "target-feature=${feat}",
  "-C", "link-arg=-fuse-ld=lld",
  "-C", "link-arg=-Wl,-z,relro,-z,now,-z,noexecstack",
]
EOF
}

export_line() {
  local args=()
  mapfile -t args < <(rustc_c_args)
  local joined=""
  local a
  for a in "${args[@]}"; do
    if [[ -n "$joined" ]]; then
      joined+=" "
    fi
    joined+="$a"
  done
  # Keep existing non-CPU RUSTFLAGS only if the caller passed EXTRA_RUSTFLAGS.
  printf "export RUSTFLAGS='%s%s'\n" "$joined" "${EXTRA_RUSTFLAGS:+ $EXTRA_RUSTFLAGS}"
}

write_cargo_config() {
  local root="${1:-}"
  if [[ -z "$root" ]]; then
    root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
  fi
  if [[ ! -f "$root/Cargo.toml" ]]; then
    echo "cpu-rustflags: no Cargo.toml under $root" >&2
    return 1
  fi
  local dest="$root/.cargo/config.toml"
  mkdir -p "$root/.cargo"
  local present
  present=$(detect_avx | tr '\n' ' ' | sed 's/[[:space:]]*$//')
  if [[ -z "$present" ]]; then
    present="(none)"
  fi
  local arr
  arr=$(toml_rustflags_array)
  cat >"$dest" <<EOF
# Generated by scripts/cpu-rustflags.sh from /proc/cpuinfo on $(hostname 2>/dev/null || uname -n) ($(date -u +%Y-%m-%dT%H:%MZ)).
# Detected AVX: ${present}
# Uses target-cpu=native: do not hardcode a microarch name.
# Host RUSTFLAGS overrides this file; unset it for these flags to apply.

[build]
rustflags = ${arr}

[target.x86_64-unknown-linux-gnu]
linker = "cc"
rustflags = ${arr}
EOF
  echo "wrote $dest"
}

cmd="${1:-print}"
case "$cmd" in
  print|"")
    rustc_c_args | paste -sd' ' -
    echo
    ;;
  features)
    detect_avx
    ;;
  export)
    export_line
    ;;
  write)
    write_cargo_config "${2:-}"
    ;;
  cargo)
    shift
    # shellcheck disable=SC1090
    eval "$(export_line)"
    exec cargo "$@"
    ;;
  -h|--help|help)
    sed -n '2,16p' "$0"
    ;;
  *)
    echo "cpu-rustflags: unknown command $cmd" >&2
    exit 2
    ;;
esac
