#!/bin/sh
# Release load test of examples/first_app on loopback. Does not bind 8082.
set -eu
BIND="${1:-127.0.0.1:8090}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
export CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-$HOME/.cache/atomos-target}"
unset RUSTFLAGS
cd "$ROOT"
BIN="${CARGO_TARGET_DIR}/release/examples/first_app"
OUT="${ROOT}/docs/bench-first-app.md"
if [ ! -x "$BIN" ]; then
	cargo build --release --example first_app
fi
case "$BIND" in
	*:8082) echo "refusing 8082" >&2; exit 2 ;;
esac
"$BIN" "$BIND" >/tmp/atomos-first-app.bench.log 2>&1 &
PID=$!
trap 'kill $PID 2>/dev/null || true; wait $PID 2>/dev/null || true' EXIT
i=0
while [ "$i" -lt 100 ]; do
	if curl -fsS --http1.1 -o /dev/null "http://${BIND}/api/health" >/dev/null 2>&1; then
		break
	fi
	i=$((i + 1))
	sleep 0.05
done
if ! curl -fsS --http1.1 -o /dev/null "http://${BIND}/api/health" >/dev/null 2>&1; then
	echo "server did not come up" >&2
	cat /tmp/atomos-first-app.bench.log >&2 || true
	exit 1
fi
python3 "$ROOT/scripts/loadtest.py" --bind "$BIND" --pid "$PID" --n 4000 --workers 4 --post-n 200 --out "$OUT.tmp"
{
	echo "# ATOMOS first_app load test"
	echo
	echo "Generated by \`scripts/bench-first-app.sh\`. Loopback \`${BIND}\`."
	echo "Host: $(uname -n) · $(grep -m1 'model name' /proc/cpuinfo | cut -d: -f2 | sed 's/^ //') · $(nproc) logical CPUs."
	echo "Binary: \`${BIN}\` (release, thin LTO)."
	echo "Server pid ${PID}. Control socket \`/tmp/atomos-first.sock\`. RSS cap 64 MiB."
	echo
	date -u +"Recorded %Y-%m-%dT%H:%MZ."
	echo
	cat "$OUT.tmp"
} > "$OUT"
rm -f "$OUT.tmp"
echo "wrote $OUT" >&2
